apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-redis-pv-volume
  namespace: blog
  labels:
    type: local
spec:
  storageClassName: blog-redis-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data1/redis"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-redis-pv-claim
  namespace: blog
spec:
  storageClassName: blog-redis-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
